### ISSUE TITLE
Naming alignment

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#2491]
## Description
ALigning the naming used across the platform

## Initiative / goal
Usage
Maintainability

### Hypothesis
By having naming clean we improve teh accessibility of the platform

## Acceptance criteria and must have scope
The following names should be updated:
- [ ] Hub ==> Community
- [ ] Canvas ==> Whiteboard
- [ ] Aspect ==> Card
- [ ] AspectTemplate ==> CardTemplate
- [ ] LifecycleTemplate ==> InnovationFlowTemplate

The following places should be updated:
- [ ] Database tables
- [ ] Server api
- [ ] Client code base
- [ ] Documentation alkemio repo

Operations backlog
- [ ] Help system on website 

## Stakeholders
Development

## Timeline

What's the timeline for this Epic, what resources are needed, and what might potentially block this from hitting the projected end date.

## Design

Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
